#!/bin/bash


echo -e "\n\n-------------------GOLINT-------------------"
golint ./...

echo -e "\n\n-------------------GO VET-------------------"
go vet ./webservice/...
go vet ./peerservice/...

echo -e "\n\n-------------------GO FMT-------------------"
go fmt ./webservice/...
go fmt ./peerservice/...

echo -e "\n\n-------------------GOCYCLO-------------------"
gocyclo ./webservice/...
gocyclo ./peerservice/...

echo -e "\n\n-------------------GO TEST-------------------"
go test ./webservice/... -cover
go test ./peerservice/... -cover